server:      
  servlet:
    context-path: /api
  port: 8080
  

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: ${postgres.url:jdbc:postgresql://localhost:5433/agente-db} 
    username: ${postgres.username:postgres} 
    password: ${postgres.password:postgres} 
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect  
    show-sql : false
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto : create-drop